CDAP-15030. Salesforce Streaming Source Integration Tests
aonischuk/salesforce-plugins pull request #10
Opened 2019-04-23 10:45 UTC by aonischuk

Integration tests do the following:
1. Start the pipeline with realtime streaming plugin as source and mockSink as sink.
2. Once the pipeline is started records are added to the remote salesforce instance specified in maven parameters
3. Than tests wait while these records are received by the pipeline.
4. The records than are asserted for correctness.

2019-04-24 09:09 UTC, mlozbin-cybervisiontech requested changes

2019-04-24 09:09 UTC, mlozbin-cybervisiontech commented on src/test/java/co/cask/hydrator/salesforce/etl/BaseSalesforceStreamingSourceETLTest.java
> +        .until(() -> MockSink.readOutput(outputManager).size() >= exceptedNumberOfRecords);
maybe untilPassed?

2019-04-24 09:09 UTC, mlozbin-cybervisiontech commented on src/test/java/co/cask/hydrator/salesforce/etl/BaseSalesforceStreamingSourceETLTest.java
> +  private boolean hasReceiverThreadStarted() {
We should not forget to think how to make same check in remoteInstance mode. Maybe wait for dummy message?

2019-04-24 09:09 UTC, mlozbin-cybervisiontech commented on src/test/java/co/cask/hydrator/salesforce/etl/BaseSalesforceStreamingSourceETLTest.java
> +  private boolean hasReceiverThreadStarted() {
at least provide an explanation of how it works and why it was done this way

2019-04-24 12:17 UTC, aonischuk commented on src/test/java/co/cask/hydrator/salesforce/etl/BaseSalesforceStreamingSourceETLTest.java
> +        .until(() -> MockSink.readOutput(outputManager).size() >= exceptedNumberOfRecords);
do you mean we should create this method? Or it is some existent thing?

2019-04-25 09:44 UTC, mlozbin-cybervisiontech approved these changes

2019-05-01 19:17 UTC, merged